version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.3
jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7-rc-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install YAPI
          command: |
            pip install -r requirements.txt
            echo "Ready to  test!"
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python yapi.py install test
  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-jessie
  test-3.3:
    <<: *test-template
    docker:
      - image: circleci/python:3.3-jessie
